name: tests

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  tests:
    name: py${{ matrix.python-version }}-${{ matrix.platform.python-architecture }}, Rust ${{ matrix.rust-toolchain }}, ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        # This list needs to be kept in sync with tag.yml and maturin_build_wheel.py.
        # TODO: Add PyPy support to tag.yml and maturin_build_wheel.py.
        python-version: [3.6, 3.7, 3.8, 3.9, pypy-3.7]
        rust-toolchain: [stable, beta, nightly]
        platform: [
          { os: "ubuntu-latest",  python-architecture: "x64", rust-target: "x86_64-unknown-linux-gnu" },
          { os: "macOS-latest",   python-architecture: "x64", rust-target: "x86_64-apple-darwin" },
          { os: "windows-latest", python-architecture: "x64", rust-target: "x86_64-pc-windows-msvc" },
          { os: "windows-latest", python-architecture: "x86", rust-target: "i686-pc-windows-msvc" },
        ]
      fail-fast: false
    env:
      CARGO_BUILD_TARGET: ${{ matrix.platform.rust-target }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.platform.python-architecture }}
      - run: python tests/python_info.py
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          target: ${{ matrix.platform.rust-target }}
          default: true
          profile: minimal
      # Install binaries from PyPI here. Install libraries below, in the
      # virtualenv.
      - run: pip install maturin virtualenv
      - run: maturin build
      - name: Run tests in a virtualenv
        run: |
          virtualenv test_virtualenv
          source test_virtualenv/bin/activate
          python --version

          # Install libraries from PyPI here. We use numpy to test the error
          # case of trying to hash a strided buffer.
          pip install pytest numpy

          # Install the built blake3 Python module in this virtualenv.
          maturin develop

          # Run tests with pytest.
          python -u -m pytest --verbose
